# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs|.git|.tox'
default_stages: [commit]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-yaml
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml

    - repo: https://github.com/pycqa/isort
      rev: 5.8.0
      hooks:
          - id: isort
            name: isort (python)

    - repo: https://github.com/psf/black.git
      rev: 21.5b0
      hooks:
          - id: black
            language_version: python3.9

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.812'
      hooks:
          - id: mypy
            files: "imia"

    - repo: local
      hooks:
          - id: pytest
            name: pytest
            entry: bash -c 'pytest'
            language: system
