# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10.0rc1']

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip poetry
                  poetry config virtualenvs.create false
                  poetry install --no-interaction

            - name: Lint with flake8
              run: |
                  flake8 imia/ tests

            - name: Lint with mypy
              run: |
                  mypy imia/

            - name: Lint with black
              run: |
                  black --check imia tests

            - name: Test with pytest
              run: |
                  pytest --no-cov-on-fail --cov imia --cov tests
